### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by pierreozoux** [idno/Subscriptions#4]
I was wondering how to reach my familly with my known instance or a familly instance.
And the email is the only solution I found. And then I discovered that plugin :)

Just to know if anybody is using it, and if it is still working?

Thanks :)

**Comment by ghost** [comment]
It is still working, I use it on my site (https://stream.tinokremer.nl/). Just drop it in your IdnoPlugins folder and have fun with it :)

**Comment by pierreozoux** [comment]
@tinokremer thank you very much, I'll try it then :)
